import { useEffect, useState, useCallback } from 'react';
import { supabase } from '../supabaseClient';
import {
  ReactFlow,
  useNodesState,
  useEdgesState,
  addEdge,
  type Connection,
  type Node,
  type Edge,
  Background,
  Controls,
  type NodeDragHandler,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

// Types for Supabase Rows
interface DbNode {
  id: string | number;
  pos_x: number;
  pos_y: number;
  label: string;
  style?: any;
}

interface DbEdge {
  id: string | number;
  source: string | number;
  target: string | number;
  label?: string;
  animated?: boolean;
  style?: any;
}

function OrgChart() {
  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [newNodeLabel, setNewNodeLabel] = useState('');
  const [editingNodeId, setEditingNodeId] = useState<string | null>(null);
  const [editingLabel, setEditingLabel] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // --- FETCH DATA ---
  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        const [nodesRes, edgesRes] = await Promise.all([
          supabase.from('nodes').select('*'),
          supabase.from('edges').select('*'),
        ]);

        if (nodesRes.error) throw nodesRes.error;
        if (edgesRes.error) throw edgesRes.error;

        const formattedNodes: Node[] = (nodesRes.data as DbNode[]).map((node) => ({
          id: node.id.toString(),
          position: { x: node.pos_x, y: node.pos_y },
          data: { label: node.label },
          style: node.style || { background: '#7c3aed', color: '#fff', borderRadius: '8px' },
        }));

        const formattedEdges: Edge[] = (edgesRes.data as DbEdge[]).map((edge) => ({
          id: edge.id.toString(),
          source: edge.source.toString(),
          target: edge.target.toString(),
          label: edge.label,
          animated: edge.animated,
          style: edge.style,
        }));

        setNodes(formattedNodes);
        setEdges(formattedEdges);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, [setNodes, setEdges]);

  // // --- CREATE NODE ---
  // const addNode = async () => {
  //   if (!newNodeLabel.trim()) return;

  //   try {
  //     const { data, error } = await supabase
  //       .from('nodes')
  //       .insert([{
  //         label: newNodeLabel,
  //         pos_x: 250,
  //         pos_y: nodes.length > 0 ? Math.max(...nodes.map(n => n.position.y)) + 100 : 100,
  //       }])
  //       .select();

  //     if (error) throw error;

  //     const newest = data[0];
  //     setNodes((nds) => [...nds, {
  //       id: newest.id.toString(),
  //       position: { x: newest.pos_x, y: newest.pos_y },
  //       data: { label: newest.label },
  //       style: newest.style
  //     }]);
  //     setNewNodeLabel('');
  //     setShowForm(false);
  //   } catch (err) {
  //     alert('Gagal menambah jawatan.');
  //   }
  // };

  const addNode = async () => {
  if (!newNodeLabel.trim()) return;

  try {
    // We only send the label; Supabase handles the ID auto-increment
    const { data, error } = await supabase
      .from('nodes')
      .insert([{ 
        label: newNodeLabel,
        pos_x: 250, 
        pos_y: 250 
      }])
      .select() // This "grabs" the auto-incremented ID back from the server
      .single();

    if (error) throw error;

    // Now 'data' contains the ID generated by the database
    const newNode: Node = {
      id: data.id.toString(), // The DB generated this for us!
      position: { x: data.pos_x, y: data.pos_y },
      data: { label: data.label },
      style: { 
        background: '#7c3aed', 
        color: '#fff', 
        borderRadius: '8px', 
        padding: '10px' 
      },
    };

    setNodes((nds) => nds.concat(newNode));
    setNewNodeLabel('');
  } catch (err) {
    console.error("Database error:", err);
    alert("Failed to save to database. Check if 'id' is set to auto-increment.");
  }
};


  // --- PERSIST DRAG POSITION ---
  const onNodeDragStop: NodeDragHandler = async (_, node) => {
    await supabase
      .from('nodes')
      .update({ pos_x: node.position.x, pos_y: node.position.y })
      .eq('id', node.id);
  };

  // --- UPDATE LABEL ---
  const updateNode = async () => {
    if (!editingNodeId || !editingLabel.trim()) return;

    try {
      const { error } = await supabase
        .from('nodes')
        .update({ label: editingLabel })
        .eq('id', editingNodeId);

      if (error) throw error;

      setNodes((nds) => nds.map(n => n.id === editingNodeId ? { ...n, data: { label: editingLabel } } : n));
      setEditingNodeId(null);
    } catch (err) {
      alert('Gagal mengemas kini.');
    }
  };

  // --- DELETE NODE ---
  const deleteNode = async (id: string) => {
    if (!window.confirm('Hapus jawatan ini?')) return;

    try {
      // Supabase RLS/Cascade usually handles edges, but if not:
      await supabase.from('edges').delete().or(`source.eq.${id},target.eq.${id}`);
      await supabase.from('nodes').delete().eq('id', id);

      setNodes((nds) => nds.filter(n => n.id !== id));
      setEdges((eds) => eds.filter(e => e.source !== id && e.target !== id));
      setSelectedNodeId(null);
    } catch (err) {
      alert('Gagal memadam.');
    }
  };

  // --- CONNECT NODES ---
  const onConnect = useCallback(async (params: Connection) => {
    const { data, error } = await supabase
      .from('edges')
      .insert([{ source: params.source, target: params.target }])
      .select();

    if (!error && data) {
      const newEdge: Edge = {
        id: data[0].id.toString(),
        source: params.source,
        target: params.target,
        animated: true
      };
      setEdges((eds) => addEdge(newEdge, eds));
    }
  }, [setEdges]);

  if (loading) return <div className="loader">Memuatkan...</div>;

  return (
    <div style={{ display: 'flex', height: '100vh', width: '100vw' }}>
      <div style={{ flex: 1 }}>
        <ReactFlow
          nodes={nodes.map(n => ({ ...n, selected: n.id === selectedNodeId }))}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          onNodeClick={(_, node) => setSelectedNodeId(node.id)}
          onNodeDragStop={onNodeDragStop}
          fitView
        >
          <Background />
          <Controls />
        </ReactFlow>
      </div>

      {/* Control Panel */}
      <div style={{ width: '300px', padding: '20px', background: '#f3f4f6', borderLeft: '1px solid #ddd' }}>
        <h3>Pengurusan Carta</h3>
        
        <button onClick={() => setShowForm(!showForm)} style={{ width: '100%', marginBottom: '10px' }}>
          {showForm ? 'Batal' : '➕ Tambah Jawatan'}
        </button>

        {showForm && (
          <div style={{ marginBottom: '20px' }}>
            <input 
              value={newNodeLabel} 
              onChange={(e) => setNewNodeLabel(e.target.value)}
              placeholder="Label baru..."
              style={{ width: '100%', padding: '5px' }}
            />
            <button onClick={addNode} style={{ marginTop: '5px' }}>Simpan</button>
          </div>
        )}

        {selectedNodeId && (
          <div style={{ border: '1px solid #3b82f6', padding: '10px', borderRadius: '5px', background: '#fff' }}>
            {editingNodeId === selectedNodeId ? (
              <>
                <input value={editingLabel} onChange={(e) => setEditingLabel(e.target.value)} style={{ width: '100%' }} />
                <button onClick={updateNode}>OK</button>
                <button onClick={() => setEditingNodeId(null)}>Batal</button>
              </>
            ) : (
              <>
                <p><strong>Pilihan:</strong> {nodes.find(n => n.id === selectedNodeId)?.data.label}</p>
                <button onClick={() => {
                  setEditingNodeId(selectedNodeId);
                  setEditingLabel(nodes.find(n => n.id === selectedNodeId)?.data.label || '');
                }}>✏️ Edit</button>
                <button onClick={() => deleteNode(selectedNodeId)} style={{ color: 'red' }}>🗑️ Padam</button>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default OrgChart;